config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  get 'profile', to: 'user#show'
  root 'welcome#index'
  resources :welcome, only: [:index, :show]
  resources :items, only: [:index, :show] do 
    resources :reviews, only: [:create]
end
resources :carts, only: [:show] do 
  resources :orders, only: [:new, :create]
end 
resources :cart_items, only: [:create, :update, :edit, :destroy]
  namespace :admin do
    resources :orders, only: [:index, :show, :edit, :update]
    root 'orders#index'
    resources :users, only: [:index, :show] do 
      member do
    resources :orders, only: [:index, :show]
      end
  end
end
  
  resources :profiles, only:[:show, :new, :create, :index, :update]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  def index
  end

  def new
    @user = safe_current_or_guest_user
    @states = 
      [
        'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 
        'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MH', 
        'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NJ', 
        'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 
        'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
      ]
  end

  def create
    @user = safe_current_or_guest_user
    profile = Profile.new(:name             => params[:name], 
                          :address          => params[:address],
                          :zipcode          => params[:zipcode],
                          :city             => params[:city],
                          :state            => params[:state],
                          :email            => params[:email], 
                          :phone_number     => params[:phone_number], 
                          :user             => safe_current_or_guest_user)
    redirect_to new_cart_order_path(@cart) if profile.save
  end

  private 
    # def profile_params 
    #   params[:user_id] = params[:user_id] == 'guest_user_id' ? current_or_guest_user : params[:user_id] 
    #     params.permit(:name, :shipping_address, :email, :phone_number, :user_id, :authenticity_token, :commit)
    #     return 
    # end 

end

app/views/profiles/index.html.erb
<h1>Already an Wynthusiast?</h1>

<%= link_to 'Sign In', new_user_session_path %> <br>

<%= form_with url: new_profile_path  %>

<%= link_to 'Check out as Guest', new_profile_path %> <br>

app/views/profiles/new.html.erb
  <div class="form"> 
  <div class= "guest">Guest Checkout</div>
    <div>
    <div >
    <%= form_with(model: @profile, url: profiles_path, method: "post") do |form| %>
      <div class="sign_up">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="sign_up">
        <%= form.label :address %>
        <%= form.text_field :address %>
      </div>
        <div class="sign_up">
        <%= form.label :zipcode %>
        <%= form.text_field :zipcode %>
      </div>
        <div class="sign_up">
        <%= form.label :city %>
        <%= form.text_field :city %>
      </div>
        <div class="sign_up">
        <%= form.label :state %>
        <%= form.select :state, @states %>
      </div>
      <div class="sign_up">
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number %>
      </div>
      <div class="sign_up">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
      <div class="checkout-button">
      <%= form.submit %>
    <% end %>

    </div>
  </div>
</div> 