config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  get 'profile', to: 'user#show'
  root 'welcome#index'
  resources :welcome, only: [:index, :show]
  resources :items, only: [:index, :show] do 
    resources :reviews, only: [:create]
end
resources :carts, only: [:show] do 
  resources :orders, only: [:new, :create]
end 
resources :cart_items, only: [:create, :update, :edit, :destroy]
  namespace :admin do
    resources :orders, only: [:index, :show, :edit, :update]
    root 'orders#index'
    resources :users, only: [:index, :show] do 
      member do
    resources :orders, only: [:index, :show]
      end
  end
end
  
  resources :profiles, only:[:show, :new, :create, :index, :update]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :user
  attribute :order_status, :integer, default: 0
  enum order_status: [:pending, :ready, :received]
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:show, :edit, :update]
  def index
      @users = User.all
      @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @cart_items = @order.cart.cart_items
    @user = @order.user
  end

  def edit 
    @statuses = [['Pending', 0], ['Ready', 1], ['Recieved', 2]];
  end 

  def update 
    @order.update(order_status: params[:order_status].to_i)
    redirect_to admin_orders_path
  end 

  private 
  def set_order 
      @order = Order.find(params[:id])
  end 

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @orders = Order.all
    end

    def show
    end

    def new 
        client = Taxjar::Client.new(ENV['TAX_KEY'])
        @rates = client.rates_for_location(@profile.zipcode).combined_rate
        @profile = safe_current_or_guest_user.profile
        @cart = Cart.find(params[:cart_id])
        @cart_items = @cart.cart_items
        @total = @cart.items.reduce(0) { |acc, item| acc + item.price.round(2) }
        @total = @total.round(2)
        @order = Order.new
    end 

    def create 
        @user = safe_current_or_guest_user
        @cart = Cart.find(params[:cart_id])
        total = @cart.items.reduce(0) { |acc, item| acc + item.price.round(2) }
        total = total.round(2)
        shipping_info_id = User.find(@user.id).profile
        order = Order.new(:cart_id => @cart.id,
                          :user_id => @user.id,
                          :total => total,
                          :shipping_info_id => shipping_info_id)
        cart = Cart.find(params[:cart_id])
        order.user = safe_current_or_guest_user
        order.cart = cart
        order.total = total
        Cart.create(user: safe_current_or_guest_user)
        stripe_total = (order.total * 100).round(2).to_i 

    customer = Stripe::Customer.create(
        :email => 'some@guy.com',
        :card  => params[:stripeToken]

    )

    charge = Stripe::Charge.create(
        :customer => customer.id,
        :amount => stripe_total,
        :description => 'description',
        :currency => 'usd'
    )

    redirect_to root_path if order.save
    
    rescue Stripe::CardError => e
        flash[:error] = e.message 
        redirect_to charges_path
    end 

end

app/views/admin/orders/edit.html.erb
<%= render 'layouts/navbar' %>
<%= render 'layouts/subnavbar' %>

<div class="admin order-details">
    <h1>Order Details</h1>
		<p><strong>Order ID:</strong> <%= @order.id%></p>
		<p><strong>E-mail address:</strong> <%= @order.user.email %></p>
		<p><strong>Grand Total:</strong> <%= @order.total%></p>
        <p><strong>Update Status:</strong><%= form_with url: admin_order_path(@order), method: 'patch', local: true do |form|  %>
        <%= form.select :order_status, options_for_select(@statuses, @order.order_status_before_type_cast) %>
            <p><strong>Order Created: </strong><%= @order.created_at.strftime("%-m/%-d/%y")%></p>
            <p><strong>Items in Order:</strong>
            <p>
                <span>Item Name</span>|
                <span>Item Price</span>|
                <span>Item Size</span>
            </p>
            <%@order.cart.cart_items.each do |item|%>
            <p>
                <span><%= item.item_size.item.item_name%>|</span>
                <span><%= item.item_size.item.price%>|</span>
                <span><%= item.item_size.size.size_name%></span>
            </p>
            <%end%>
            <%= form.submit 'Update Order' %>
        <% end %>
</div>

app/views/admin/orders/index.html.erb
<%= render 'layouts/navbar' %>
<%= render 'layouts/subnavbar' %>
<div class="admin all-orders">
<h1>All Orders</h1>

<%if @orders.present?%>

	<table class="all-orders-table" style="">
    <tr>
    <th>Order #</th>
    <th>E-mail</th>
    <th>Order Total</th>
    <th>Order Status</th>
    <th>Order Date</th>
    </tr>

    <% @orders.each do |order| %>
    
    <tr>
      <td><%= order.id%></td>
      <td><%= link_to order.user.email, edit_admin_order_path(order) %></td>
      <td><%= order.total%></td>
      <td><%= order.order_status%></td>
      <td><%= order.created_at%></td>
    </tr>
<% end %>

	</table>
<%else%>
	<p>No orders!</p>
<% end%>
</div>