config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  get 'profile', to: 'user#show'
  root 'welcome#index'
  resources :welcome, only: [:index, :show]
  resources :items, only: [:index, :show] do 
    resources :reviews, only: [:create]
end
resources :carts, only: [:show] do 
  resources :orders, only: [:new, :create]
end 
resources :cart_items, only: [:create, :update, :edit, :destroy]
  namespace :admin do
    resources :orders, only: [:index, :show, :edit, :update]
    root 'orders#index'
    resources :users, only: [:index, :show] do 
      member do
    resources :orders, only: [:index, :show]
      end
  end
end
  
  resources :profiles, only:[:show, :new, :create, :index, :update]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :item_sizes, through: :cart_items
  has_many :items, through: :item_sizes
  has_one :order

  def create
    @cart = Cart.create()
    @item = Item.find(params[:recipe_id])
  end

  def show
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
    @cartItems = @cart.cart_items
    @user = @cart.user
    @profile = @cart.user&.profile&.name
  end
end

app/views/carts/show.html.erb
<%= render 'layouts/navbar' %>
<%= render 'layouts/subnavbar' %>

<div class="shopping-cart-page-container">
  <div class="shopping-cart-page-title"><h1>Shopping cart</h1></div>
  <% total = 0.0 %>
  <% if @cartItems.present? %>
  <div class="display-items-cart">
    <div class="display-items-cart-title">
      <h1>Items</h1>
    </div>
        <% @cartItems.each do |item| %>
          <% total = total + item.item_size.item.price %>
          <div class="item-description-wrapper">
            <div class="item-picture">
              <%= image_tag(item.item_size.item.itemURL)%>
            </div>
            <div class="item-description">
              <div class="item-name"><%= item.item_size.item.item_name %></div>
              <div class="item-size"><%= item.item_size.size.size_name %></div>
              <div class="item-price">$<%= item.item_size.item.price %></div>
              <div >
                      <%= button_to 'Delete Item', cart_item_path(item),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: "item-delete" %>
              </div>
            </div>
            <div class="item-separator"></div>
          </div>
        <%end%>
        <div class="cart-subtotal">
          <div class="subtotal-attribute">Cart Subtotal:</div>
          <div class="subtotal-value"> <%= number_to_currency(total)%>
        </div>
  </div>
  <div class="end-of-item-list"></div>
  <div class="checkout-button">
  <% if @profile %>
    <%= link_to 'Checkout', new_cart_order_path(@cart) %>
  <% else %>
      <%= link_to 'Checkout', new_profile_path %>
  <% end%>
  </div>
  <div class="continue-shopping">
    <%= link_to "Continue Shopping", items_path%>
  </div>
  <% else %>
    <div class="display-items-cart-title">
      <h1> Cart is empty, shop for items now!</h1>
    </div>
  <% end %>
</div>