config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  get 'profile', to: 'user#show'
  root 'welcome#index'
  resources :welcome, only: [:index, :show]
  resources :items, only: [:index, :show] do 
    resources :reviews, only: [:create]
end
resources :carts, only: [:show] do 
  resources :orders, only: [:new, :create]
end 
resources :cart_items, only: [:create, :update, :edit, :destroy]
  namespace :admin do
    resources :orders, only: [:index, :show, :edit, :update]
    root 'orders#index'
    resources :users, only: [:index, :show] do 
      member do
    resources :orders, only: [:index, :show]
      end
  end
end
  
  resources :profiles, only:[:show, :new, :create, :index, :update]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :item_sizes, through: :cart_items
  has_many :items, through: :item_sizes
  has_one :order

  def create
    @cart = Cart.create()
    @item = Item.find(params[:recipe_id])
  end

  def show
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item_size
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :cart_item, dependent: :destroy
  has_many :item_sizes
  has_many :sizes, through: :item_sizes
  has_many :item_images

  def average_rating
    return 0 if reviews.empty?
    (reviews.where.not(rating: nil).reduce(0) { |acc, review| acc + review.rating } / reviews.length).round
  end
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item
end

app/models/item_size.rb
class ItemSize < ApplicationRecord
  belongs_to :item
  belongs_to :size
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :user
  attribute :order_status, :integer, default: 0
  enum order_status: [:pending, :ready, :received]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items, through: :item_sizes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders,  dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
    @cartItems = @cart.cart_items
    @user = @cart.user
    @profile = @cart.user&.profile&.name
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @items_by_category = Item.all.group_by { |item| item.category }
    @category_keys = @items_by_category.keys

  end

  def show 
    @item = Item.find(params[:id])
    @sizes = @item.sizes.map { |size| size.size_name }
    @reviews = Review.where(item_id: @item.id)
    @poses = @item.item_images
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @orders = Order.all
    end

    def show
    end

    def new 
        client = Taxjar::Client.new(ENV['TAX_KEY'])
        @rates = client.rates_for_location(@profile.zipcode).combined_rate
        @profile = safe_current_or_guest_user.profile
        @cart = Cart.find(params[:cart_id])
        @cart_items = @cart.cart_items
        @total = @cart.items.reduce(0) { |acc, item| acc + item.price.round(2) }
        @total = @total.round(2)
        @order = Order.new
    end 

    def create 
        @user = safe_current_or_guest_user
        @cart = Cart.find(params[:cart_id])
        total = @cart.items.reduce(0) { |acc, item| acc + item.price.round(2) }
        total = total.round(2)
        shipping_info_id = User.find(@user.id).profile
        order = Order.new(:cart_id => @cart.id,
                          :user_id => @user.id,
                          :total => total,
                          :shipping_info_id => shipping_info_id)
        cart = Cart.find(params[:cart_id])
        order.user = safe_current_or_guest_user
        order.cart = cart
        order.total = total
        Cart.create(user: safe_current_or_guest_user)
        stripe_total = (order.total * 100).round(2).to_i 

    customer = Stripe::Customer.create(
        :email => 'some@guy.com',
        :card  => params[:stripeToken]

    )

    charge = Stripe::Charge.create(
        :customer => customer.id,
        :amount => stripe_total,
        :description => 'description',
        :currency => 'usd'
    )

    redirect_to root_path if order.save
    
    rescue Stripe::CardError => e
        flash[:error] = e.message 
        redirect_to charges_path
    end 

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  def index
  end

  def new
    @user = safe_current_or_guest_user
    @states = 
      [
        'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 
        'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MH', 
        'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NJ', 
        'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 
        'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
      ]
  end

  def create
    @user = safe_current_or_guest_user
    profile = Profile.new(:name             => params[:name], 
                          :address          => params[:address],
                          :zipcode          => params[:zipcode],
                          :city             => params[:city],
                          :state            => params[:state],
                          :email            => params[:email], 
                          :phone_number     => params[:phone_number], 
                          :user             => safe_current_or_guest_user)
    redirect_to new_cart_order_path(@cart) if profile.save
  end

  private 
    # def profile_params 
    #   params[:user_id] = params[:user_id] == 'guest_user_id' ? current_or_guest_user : params[:user_id] 
    #     params.permit(:name, :shipping_address, :email, :phone_number, :user_id, :authenticity_token, :commit)
    #     return 
    # end 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def create
    @item = Item.find(params[:item_id])
    @review = @item.reviews.new(review_params)
    @review.user = current_user
    redirect_to @item if @review.save
  end
  
    def index
      @Reviews = Review.all
    end

    private

  def review_params
    params.require(:review).permit(:rating, :comments)
  end

  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @items = Item.all
    @items_by_category = Item.all.group_by { |item| item.category }
    @category_keys = @items_by_category.keys

  end

  def show 
    @item = Item.find(params[:id])
    @sizes = @item.sizes.map { |size| size.size_name }
    @reviews = Review.where(item_id: @item.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/shippings/index.html.erb
<h1>Users Shippings View</h1>

<% @shippings.each do |ship|%>
<%= shippings.all %>

<% end %>

app/views/layouts/_homenavbar.html.erb
<nav>
  <div class="home-navigation-bar">
    <div class="navbar-logo-name">
      <%=image_tag("logo.svg") %>
      <%= link_to "Wynstore",welcome_index_path  %>
    </div>
    <div class="navbar-right">
      <div class= "login-or-register">
        <% unless current_user %>
            <%= link_to 'Login ', user_session_path %>
          /
            <%= link_to ' Register', new_user_registration_path %>
        <% else %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> 
        <% end %>
      </div>
      <div class="shopping-cart-icon">
        <div>
          <%= link_to cart_path(safe_current_or_guest_user.carts.last) do %>
            <i class="fas fa-shopping-cart fa-4x"></i>
          <% end %>
        </div>
          <div class="cart-item-count"><%="#{safe_current_or_guest_user.carts.last.items.count}"%></div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="navigation-bar">
    <div class="navbar-logo-name">
      <%=image_tag("logo.svg") %>
      <%= link_to "Wynstore",welcome_index_path  %>
    </div>
    <div class="navbar-right">
      <div class= "login-or-register">
        <% unless current_user %>
            <%= link_to 'Login ', user_session_path %>
          /
            <%= link_to ' Register', new_user_registration_path %>
        <% else %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> 
        <% end %>
      </div>
      <div class="shopping-cart-icon">
        <div>
          <%= link_to cart_path(safe_current_or_guest_user.carts.last) do %>
            <i class="fas fa-shopping-cart fa-4x"></i>
          <% end %>
        </div>
          <div class="cart-item-count"><%="#{safe_current_or_guest_user.carts.last.items.count}"%></div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_subnavbar.erb
<% if safe_current_or_guest_user.admin? %>
    <div class="sub-nav">
      <span id="links-1">
        <%= link_to 'Orders', admin_orders_path %>
      </span>
      <span class="arrow"> 
        | 
      </span>
      <span id="links-2">
        <%= link_to 'Users', admin_users_path %>

      </span>


    </div>
  <%else%>
    <div class="sub-nav">
      <span id="links-1">
        <%= link_to 'Home', welcome_index_path %>
      </span>
      <span class="arrow"> 
        > 
      </span>
      <span id="links-2">
        <%= link_to 'Items', items_path %>
      <span class="arrow"> 
        > 
      </span>
      <span id="links-3">
        <%= link_to 'Cart', cart_path(safe_current_or_guest_user.carts.last) %>
      </span>
    <div>
<%end%>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Wynstore!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600|Rajdhani:300,400,600&display=swap" rel="stylesheet">
    <script 
      src="https://kit.fontawesome.com/e6601b1b2e.js" 
      crossorigin="anonymous"
    ></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/0b06feec75.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<tbody>
  <%= yield %>
 <tbody>
 </html> 

app/views/layouts/create.html.erb
<h2>Thanks, you paid<strong>$25.00</strong>For a great Shirt!</h2>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
(<%= current_user.email %>)
<%= react_component 'App' %>